### ISSUE TITLE
Integrate Codecov

### ISSUE THREAD

**Issue by CasperLaiTW** [codebar-ag/Laravel-Prerender#17]
I added some tests, and maybe find a service for showing test coverage?

I found Codecov. if you can setup it will be good, have to access organization.

if you have alternative service, also put on the list. we can integrate.

**Comment by StanBarrows** [comment]
Github Actions with PEST?

```
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: ./vendor/bin/pest --coverage --min=25
```

https://pestphp.com/

**Comment by StanBarrows** [comment]
I've added the Codecov Token via Secrets.

![image](https://user-images.githubusercontent.com/10268813/93661271-c8ba3780-fa56-11ea-98e8-dbd28a6afee4.png)

**Comment by CasperLaiTW** [comment]
> Github Actions with PEST?
> 
> ```
>       - name: Execute tests (Unit and Feature tests) via PHPUnit
>         run: ./vendor/bin/pest --coverage --min=25
> ```
> 
> https://pestphp.com/

Bit hard to use `pestphp`

> Pest requires PHP 7.3+ to work.

and we need to test in PHP 7.2

**Comment by StanBarrows** [comment]
Youre're right, thx!

So let's give it a try.
