### ISSUE TITLE
Prerender Requests Hang & Don't Timeout

### ISSUE THREAD

**Issue by kellerjmrtn** [codebar-ag/laravel-prerender#38]
### Feature

On prerenderable pages, the `PrerenderMiddleware` makes an HTTP request to prerender for the prerendered page data. For an unknown reason in my app (still researching why), this request hangs and a response is never returned. My apache config is set to time requests out after 60s, so I'm seeing occasional 503 responses in my logs due to this timeout being hit. I've traced it back to the HTTP request made by the `PrerenderMiddleware`, and it's only happening very infrequently.

As a temporary fix in my app, I've set a `timeout` value (see [guzzle docs](https://docs.guzzlephp.org/en/stable/request-options.html#timeout)) on the guzzle `Client` instance being used. If this timeout is hit, a `GuzzleHttp\Exception\ConnectException` is thrown, which I then catch and run `$next($request)`. So instead of failing due to a prerender issue, I just return the real page, as a temporary fix.

It was a pretty simple addition, like so

### In Service Provider

```
$this->app->bind(PrerenderMiddleware::class, function ($app) {
    return new CustomPrerenderMiddleware(new Client([
        'timeout' => $app->config->get('prerender.timeout'),
    ]));
});
```

### In Middleware
```
class CustomPrerenderMiddleware extends PrerenderMiddleware
{
    public function handle(Request $request, Closure $next)
    {
        try {
            return parent::handle($request, $next);
        } catch (ConnectException $e) {
            // ConnectException will be thrown if the prerender request times out
            Log::error($e);
        }

        // If caught, simply process the request without prerender
        return $next($request);
    }
}
```

I think this would be a good improvement to have in the project itself, as most users likely wouldn't want a timeout here to affect their app. The current middleware also already catches `GuzzleHttp\Exception\RequestException`, so it may just be more consistent to catch this as well

The timeout could be done in a backwards compatible way, by setting a default value of `0`, meaning no timeout

I would be willing to make a PR for this, if desired

**Comment by StanBarrows** [comment]
Hey @kellerjmrtn 

Thanks for your message & time.

I would merge such a PR.

Best regards
Sebastian

**Comment by StanBarrows** [comment]
v11.1 published,
