### ISSUE TITLE
Update Documentation | How to test it?

### ISSUE THREAD

**Issue by StanBarrows** [codebar-ag/Laravel-Prerender#7]
Would be great to show how to test if it works. Because in my prerender.io Dashboard there is currently no possibility to see any stats. So I'm not quite sure if it works 100% correctly.

![image](https://user-images.githubusercontent.com/10268813/93469131-57607480-f8f0-11ea-8867-db2b1ef368e1.png)

**Comment by CasperLaiTW** [comment]
I will do some tests in the weekend. 

If you have any update, just let know 👍

**Comment by CasperLaiTW** [comment]
@StanBarrows I did some tested. it's working.

https://github.com/CasperLaiTW/laravel-prerender-example

![截圖 2020-09-18 上午9 53 45](https://user-images.githubusercontent.com/5094008/93546492-6fd69a80-f995-11ea-83b6-63f15cb66b8c.png)


just add `_escaped_fragment_=` in url query string, it will trigger prerender middleware

**Comment by CasperLaiTW** [comment]
and I think documentation already write about how it works

https://github.com/codebar-ag/Laravel-Prerender#how-it-works

I create new PR for update documentation, remove some configuration.

you can update it too if it's not clear

**Comment by StanBarrows** [comment]
Thanks a lot, i guess it was somehow missing that we need to apply the Middleware at some point.
